version: 2

# NOTE: partial seconds do not work; whole seconds only.
reversion:
  # How many seconds to wait before initially starting reverting
  initial-delay: 30
  # How many seconds in between blocks
  loop-delay: 1
