main: me.rileycalhoun.explosionreverter.ExplosionReverter
name: ExplosionReverter
description: Reverts explosion after a set amount of time.
version: 1.1.1
api-version: 1.21
author: Riley Calhoun

permissions:
  explosionreverter.*:
    description: All ExplosionReverter permissions
    default: op
    children:
      explosionreverter.command: true
  explosionreverter.command:
    description: Use /explosionreverter and /explosionreverter reload
    default: op

commands:
  explosionreverter:
    description: Reload the ExplosionReverter config.
    aliases: er